name: esc_pos_utils
description: Basic Flutter/Dart classes for ESC/POS printing. Ticket class generates ESC/POS commands that can be sent to a thermal printer.
version: 2.0.0
homepage: https://github.com/andrey-ushakov/esc_pos_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hex: 
    git:
      url: https://github.com/kechankrisna/dart-hex.git
      ref: nullable
  gbk_codec: 
    git:
      url: https://github.com/kechankrisna/gbk_codec.git
      ref: master
  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/esc_pos_utils/resources/capabilities.json
